var achievements = {
  "timber": {
    "title" : "TIMBER!!!",
    "description" : "Chop down your first tree.",
    "image" : [64,160],
    "reward" : ["clean","clean","clean","none"],
    "completed" : false,
  },
  "mine": {
    "title" : "It's All Mine!",
    "description" : "Mine your first rock.",
    "image" : [96,160],
    "reward" : ["grey","grey","grey","none"],
    "completed" : false,
  },
  "shiny": {
    "title" : "Shiny Rocks!",
    "description" : "Collect one of each type of gem.",
    "image" : [0,64],
    "reward" : ["blue","blue","blue","none"],
    "completed" : false,
  },
  "uranium": {
    "title" : "Uranium Fever",
    "description" : "Collect a lump of radioactive uranium ore.",
    "image" : [288,224],
    "reward" : ["green","green","green","none"],
    "completed" : false,
  },
  "alive": {
    "title" : "It's Alive!",
    "description" : "Enable skin parts from three different sets at the same time.",
    "image" : [288,224],
    "reward" : ["none", "none", "none", "frankenstein"],
    "completed" : false,
  },
  "liftoff": {
    "title" : "Lift Off!",
    "description" : "Lift off in a rocket.",
    "image" : [128,160],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  
  
  
  "ocean": {
    "title" : "Biome: Ocean",
    "description" : "Discover an Ocean biome.",
    "image" : [0,0],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "snow": {
    "title" : "Biome: Snow",
    "description" : "Discover a Snow biome.",
    "image" : [32,0],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "tundra": {
    "title" : "Biome: Tundra",
    "description" : "Discover a Tundra biome.",
    "image" : [64,0],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "plains": {
    "title" : "Biome: Plains",
    "description" : "Discover a Plains biome.",
    "image" : [96,0],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "swamp": {
    "title" : "Biome: Swamp",
    "description" : "Discover a Swamp biome.",
    "image" : [128,0],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "savannah": {
    "title" : "Biome: Savannah",
    "description" : "Discover a Savannah biome.",
    "image" : [160,0],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "desert": {
    "title" : "Biome: Desert",
    "description" : "Discover a Desert biome.",
    "image" : [192,0],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "volcano": {
    "title" : "Biome: Volcano",
    "description" : "Discover a Volcano biome.",
    "image" : [224,0],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  
  
  
  "copper": {
    "title" : "Call the Coppers!",
    "description" : "Collect some copper ore.",
    "image" : [0,224],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "iron": {
    "title" : "Isn't it Ironic?",
    "description" : "Collect some iron ore.",
    "image" : [32,224],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "gold": {
    "title" : "Gold Digger",
    "description" : "Collect some gold ore.",
    "image" : [64,224],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "tin": {
    "title" : "Tin Foil Hats",
    "description" : "Collect some tin ore.",
    "image" : [96,224],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "cobalt": {
    "title" : "Got the Blues",
    "description" : "Collect some cobalt ore.",
    "image" : [192,224],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "titanium": {
    "title" : "Strenght of a Titan",
    "description" : "Collect some titanium ore.",
    "image" : [224,224],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "osmium": {
    "title" : "What's this Osmium stuff?",
    "description" : "Collect some osmium ore.",
    "image" : [256,224],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "silver": {
    "title" : "Long John Silver",
    "description" : "Collect some silver ore.",
    "image" : [320,224],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "lead": {
    "title" : "Lead The Way!",
    "description" : "Collect some lead ore.",
    "image" : [352,224],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  
  "diamond": {
    "title" : "Shiny Blue Rocks",
    "description" : "Collect a beautiful diamond.",
    "image" : [0,64],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "sapphire": {
    "title" : "Deep Blue Gems",
    "description" : "Collect a beautiful sapphire.",
    "image" : [32,64],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "jade": {
    "title" : "This Gem Looks Like A Cucumber!",
    "description" : "Collect a beautiful jade.",
    "image" : [64,64],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "emerald": {
    "title" : "Emerald Hills",
    "description" : "Collect a beautiful emerald.",
    "image" : [96,64],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "topaz": {
    "title" : "Top(az) Trumps",
    "description" : "Collect a beautiful topaz.",
    "image" : [128,64],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "ruby": {
    "title" : "Blood Red Stone",
    "description" : "Collect a beautiful ruby.",
    "image" : [160,64],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "coal": {
    "title" : "Naughty List",
    "description" : "Collect a lump of coal. You've been naughty this year!",
    "image" : [0,160],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  "stone": {
    "title" : "Pretty Large Pebble",
    "description" : "Collect a lump of stone. That's one big pebble!",
    "image" : [96,160],
    "reward" : ["none","none","none","none"],
    "completed" : false,
  },
  
  "hyperspace": {
    "title" : "Commencing Jump...",
    "description" : "Build a hyperdrive and escape the solar system.",
    "image" : [128,160],
    "reward" : ["gold","gold","gold","none"],
    "completed" : false,
  },
};