var stats = {
  "trees_harvested" : 0,
  "rocks_harvested" : 0,
  
  "tiles_moved" : 0,
  
  "biome_visited.ocean" : 0,
  "biome_visited.snow" : 0,
  "biome_visited.tundra" : 0,
  "biome_visited.plains" : 0,
  "biome_visited.swamp" : 0,
  "biome_visited.savannah" : 0,
  "biome_visited.desert" : 0,
  "biome_visited.volcano" : 0,
  
  "item.ore.copper_collected" : 0,
  "item.ore.iron_collected" : 0,
  "item.ore.gold_collected" : 0,
  "item.ore.tin_collected" : 0,
  "item.ore.cobalt_collected" : 0,
  "item.ore.titanium_collected" : 0,
  "item.ore.osmium_collected" : 0,
  "item.ore.uranium_collected" : 0,
  "item.ore.silver_collected" : 0,
  "item.ore.lead_collected" : 0,
  "item.ore.nickel_collected" : 0,
  "item.ore.coal_collected" : 0,
  "item.ore.wood_collected" : 0,
  "item.ore.stone_collected" : 0,
  "item.gem.diamond_collected" : 0,
  "item.gem.sapphire_collected" : 0,
  "item.gem.jade_collected" : 0,
  "item.gem.emerald_collected" : 0,
  "item.gem.topaz_collected" : 0,
  "item.gem.ruby_collected" : 0,
  
  "item.stone_collected" : 0,
  "item.coal_collected" : 0,
  "item.wood_collected" : 0,
};